name: Basic NodeJS build

on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: ['12']
    name: Install NodeJS deps, source code, and run tests
    steps:
    - name: Checkout repository source code
      uses: actions/checkout@v2

    - name: Cache NPM directory for faster future builds
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install deps
      working-directory: refresher
      run: npm install

    - name: Run unit tests
      working-directory: refresher
      run: npm run test:coverage
